/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PathAscendingRouteImport } from './routes/path/ascending'
import { Route as PathStarterRouteImport } from './routes/path/starter'
import { Route as ApiOauthCallbackRouteImport } from './routes/api/oauth/callback'
import { Route as ApiOauthLoginRouteImport } from './routes/api/oauth/login'
import { Route as ApiOauthLogoutRouteImport } from './routes/api/oauth/logout'
import { Route as ApiWebhooksWhopRouteImport } from './routes/api/webhooks/whop'
import { Route as PathCommunityIndexRouteImport } from './routes/path/community/index'
import { Route as PathCommunityAdminRouteImport } from './routes/path/community/admin'
import { Route as PathDeeperSectionLessonRouteImport } from './routes/path/deeper/$section/$lesson'
import { Route as PathModulePlanTrackLessonRouteImport } from './routes/path/module/$plan/$track/$lesson'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PathAscendingRoute = PathAscendingRouteImport.update({
  id: '/path/ascending',
  path: '/path/ascending',
  getParentRoute: () => rootRouteImport,
} as any)
const PathStarterRoute = PathStarterRouteImport.update({
  id: '/path/starter',
  path: '/path/starter',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthCallbackRoute = ApiOauthCallbackRouteImport.update({
  id: '/api/oauth/callback',
  path: '/api/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLoginRoute = ApiOauthLoginRouteImport.update({
  id: '/api/oauth/login',
  path: '/api/oauth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLogoutRoute = ApiOauthLogoutRouteImport.update({
  id: '/api/oauth/logout',
  path: '/api/oauth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksWhopRoute = ApiWebhooksWhopRouteImport.update({
  id: '/api/webhooks/whop',
  path: '/api/webhooks/whop',
  getParentRoute: () => rootRouteImport,
} as any)
const PathCommunityIndexRoute = PathCommunityIndexRouteImport.update({
  id: '/path/community/',
  path: '/path/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const PathCommunityAdminRoute = PathCommunityAdminRouteImport.update({
  id: '/path/community/admin',
  path: '/path/community/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PathDeeperSectionLessonRoute = PathDeeperSectionLessonRouteImport.update({
  id: '/path/deeper/$section/$lesson',
  path: '/path/deeper/$section/$lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const PathModulePlanTrackLessonRoute =
  PathModulePlanTrackLessonRouteImport.update({
    id: '/path/module/$plan/$track/$lesson',
    path: '/path/module/$plan/$track/$lesson',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dmca': typeof DmcaRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/path/ascending': typeof PathAscendingRoute
  '/path/starter': typeof PathStarterRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
  '/api/webhooks/whop': typeof ApiWebhooksWhopRoute
  '/path/community/admin': typeof PathCommunityAdminRoute
  '/path/community/': typeof PathCommunityIndexRoute
  '/path/deeper/$section/$lesson': typeof PathDeeperSectionLessonRoute
  '/path/module/$plan/$track/$lesson': typeof PathModulePlanTrackLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dmca': typeof DmcaRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/path/ascending': typeof PathAscendingRoute
  '/path/starter': typeof PathStarterRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
  '/api/webhooks/whop': typeof ApiWebhooksWhopRoute
  '/path/community/admin': typeof PathCommunityAdminRoute
  '/path/community': typeof PathCommunityIndexRoute
  '/path/deeper/$section/$lesson': typeof PathDeeperSectionLessonRoute
  '/path/module/$plan/$track/$lesson': typeof PathModulePlanTrackLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dmca': typeof DmcaRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/path/ascending': typeof PathAscendingRoute
  '/path/starter': typeof PathStarterRoute
  '/api/oauth/callback': typeof ApiOauthCallbackRoute
  '/api/oauth/login': typeof ApiOauthLoginRoute
  '/api/oauth/logout': typeof ApiOauthLogoutRoute
  '/api/webhooks/whop': typeof ApiWebhooksWhopRoute
  '/path/community/admin': typeof PathCommunityAdminRoute
  '/path/community/': typeof PathCommunityIndexRoute
  '/path/deeper/$section/$lesson': typeof PathDeeperSectionLessonRoute
  '/path/module/$plan/$track/$lesson': typeof PathModulePlanTrackLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dmca'
    | '/privacy'
    | '/terms'
    | '/path/ascending'
    | '/path/starter'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
    | '/api/webhooks/whop'
    | '/path/community/admin'
    | '/path/community/'
    | '/path/deeper/$section/$lesson'
    | '/path/module/$plan/$track/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dmca'
    | '/privacy'
    | '/terms'
    | '/path/ascending'
    | '/path/starter'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
    | '/api/webhooks/whop'
    | '/path/community/admin'
    | '/path/community'
    | '/path/deeper/$section/$lesson'
    | '/path/module/$plan/$track/$lesson'
  id:
    | '__root__'
    | '/'
    | '/dmca'
    | '/privacy'
    | '/terms'
    | '/path/ascending'
    | '/path/starter'
    | '/api/oauth/callback'
    | '/api/oauth/login'
    | '/api/oauth/logout'
    | '/api/webhooks/whop'
    | '/path/community/admin'
    | '/path/community/'
    | '/path/deeper/$section/$lesson'
    | '/path/module/$plan/$track/$lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DmcaRoute: typeof DmcaRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  PathAscendingRoute: typeof PathAscendingRoute
  PathStarterRoute: typeof PathStarterRoute
  ApiOauthCallbackRoute: typeof ApiOauthCallbackRoute
  ApiOauthLoginRoute: typeof ApiOauthLoginRoute
  ApiOauthLogoutRoute: typeof ApiOauthLogoutRoute
  ApiWebhooksWhopRoute: typeof ApiWebhooksWhopRoute
  PathCommunityAdminRoute: typeof PathCommunityAdminRoute
  PathCommunityIndexRoute: typeof PathCommunityIndexRoute
  PathDeeperSectionLessonRoute: typeof PathDeeperSectionLessonRoute
  PathModulePlanTrackLessonRoute: typeof PathModulePlanTrackLessonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/ascending': {
      id: '/path/ascending'
      path: '/path/ascending'
      fullPath: '/path/ascending'
      preLoaderRoute: typeof PathAscendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/starter': {
      id: '/path/starter'
      path: '/path/starter'
      fullPath: '/path/starter'
      preLoaderRoute: typeof PathStarterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/callback': {
      id: '/api/oauth/callback'
      path: '/api/oauth/callback'
      fullPath: '/api/oauth/callback'
      preLoaderRoute: typeof ApiOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/login': {
      id: '/api/oauth/login'
      path: '/api/oauth/login'
      fullPath: '/api/oauth/login'
      preLoaderRoute: typeof ApiOauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/logout': {
      id: '/api/oauth/logout'
      path: '/api/oauth/logout'
      fullPath: '/api/oauth/logout'
      preLoaderRoute: typeof ApiOauthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/whop': {
      id: '/api/webhooks/whop'
      path: '/api/webhooks/whop'
      fullPath: '/api/webhooks/whop'
      preLoaderRoute: typeof ApiWebhooksWhopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/community/': {
      id: '/path/community/'
      path: '/path/community'
      fullPath: '/path/community/'
      preLoaderRoute: typeof PathCommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/community/admin': {
      id: '/path/community/admin'
      path: '/path/community/admin'
      fullPath: '/path/community/admin'
      preLoaderRoute: typeof PathCommunityAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/deeper/$section/$lesson': {
      id: '/path/deeper/$section/$lesson'
      path: '/path/deeper/$section/$lesson'
      fullPath: '/path/deeper/$section/$lesson'
      preLoaderRoute: typeof PathDeeperSectionLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path/module/$plan/$track/$lesson': {
      id: '/path/module/$plan/$track/$lesson'
      path: '/path/module/$plan/$track/$lesson'
      fullPath: '/path/module/$plan/$track/$lesson'
      preLoaderRoute: typeof PathModulePlanTrackLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DmcaRoute: DmcaRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  PathAscendingRoute: PathAscendingRoute,
  PathStarterRoute: PathStarterRoute,
  ApiOauthCallbackRoute: ApiOauthCallbackRoute,
  ApiOauthLoginRoute: ApiOauthLoginRoute,
  ApiOauthLogoutRoute: ApiOauthLogoutRoute,
  ApiWebhooksWhopRoute: ApiWebhooksWhopRoute,
  PathCommunityAdminRoute: PathCommunityAdminRoute,
  PathCommunityIndexRoute: PathCommunityIndexRoute,
  PathDeeperSectionLessonRoute: PathDeeperSectionLessonRoute,
  PathModulePlanTrackLessonRoute: PathModulePlanTrackLessonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
